version: "3.9"
services:
  database:
    image: "postgres:14.0-alpine" # use latest official postgres version
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
