openapi: 3.0.0
servers:
  - url: http://petstore.swagger.io/v1
info:
  version: "1"
  title: "demo petstore API"
paths:
  /pet/{name}:
    put:
      operationId: updatePet
      x-scala-package: pet
      parameters:
        - name: name
          in: path
          schema:
            type: string
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
                $ref: "#/components/schemas/Pet"
      responses:
        "200":
          description: ""
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/Pet"
  /pets:
    post:
      operationId: createPet
      x-scala-package: pet
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              properties:
                name:
                  type: string
                status:
                  type: string
              required:
                - name
      responses:
        "200":
          description: ""
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/Pet"
components:
  schemas:
    Pet:
      type: object
      required:
      - name
      properties:
        name:
          type: string
        status:
          type: string
